server {
  listen 8080;
  # for every request return index.html 
  location / { root /usr/share/nginx/html; index index.html; }
}

server {
  listen 8081;
  # on status code 501 return custom_501.html
  error_page 501 /custom_501.html;
  # for every request return status code 501 
  location / { return 501; }

  location = /custom_501.html {
    root /usr/share/nginx/html;
    internal;
  }
}
